# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - task: GoTool@0
    inputs:
      version: '1.13.4'
    displayName: Installing go

  - script: |
      go build -v .
    displayName: 'Get dependencies, then build'

  - script: go test -v ./...
    displayName: 'Run unit tests'

  - script: go build -o examples/oauth2local
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Building for integration tests'

  - task: DockerCompose@0
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Run integration tests'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: 'examples/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'up --build --exit-code-from integration'
      cwd: '$(System.DefaultWorkingDirectory)/examples'
