# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: GoTool@0
  inputs:
    version: '1.12'
  displayName: Installing go

- script: |
    go version
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
    go build -v .
  displayName: 'Get dependencies, then build'

- script: go test -v ./...
  displayName: 'Run unit tests'

- script: go build -o examples/oauth2local
  displayName: 'Building for integration tests'

- task: DockerCompose@0
  displayName: 'Run integration tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '$(Build.Repository.LocalPath)/examples/docker-compose.yml'
    action: 'Run services'